package com.company.chapter13;

/*
    Return from Finally: In Java, does the finally block get executed if we insert a return statement
    inside the try block of a try-catch-finally?

    Answer: Yes. In some cases, it won't executed such as
    1. VM terminates in try catch block.
    2. Thread terminates in try catch block

 */
public class Q13_2 {
}
